version: '3.8'

services:
  database:
    image: 'mongo'
    restart: always
    container_name: 'database'
    network_mode: 'host'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admn
      - MONGO_INITDB_ROOT_PASSWORD=mudar123
  
  api:
    build: .
    container_name: 'api'
    network_mode: 'host'
