version: '3.8'

services:
  database:
    image: 'mongo'
    restart: always
    container_name: 'database'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - ${MONGO_EXTERNAL_PORT}:27017
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.1
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - 9200:9200

  graylog:
    image: graylog/graylog:3.0
    environment:
      GRAYLOG_PASSWORD_SECRET: '${GRAYLOG_PASSWORD_SECRET}'
      # Password: admin
      GRAYLOG_ROOT_PASSWORD_SHA2: '${GRAYLOG_PASSWORD_SHA2}'
      GRAYLOG_HTTP_EXTERNAL_URI: 'http://localhost:${GRAYLOG_EXTERNAL_PORT}/'
      GRAYLOG_MONGODB_URI: "mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@database:27017/graylog?authSource=admin"
      GRAYLOG_ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:${GRAYLOG_EXTERNAL_PORT}"
    depends_on:
      - database
      - elasticsearch
    links:
      - database
      - elasticsearch
    ports:
      - ${GRAYLOG_EXTERNAL_PORT}:9000 # Graylog web interface and REST API
      - 5555:5555 # Raw/Plaintext TCP
      - 1514:1514 # Syslog TCP
      - 1514:1514/udp # Syslog UDP
      - 12201:12201 # GELF TCP
      - 12201:12201/udp # GELF UDP

  api:
    build: .
    container_name: 'api'
    ports:
      - ${API_EXTERNAL_PORT}:3000
